import React from 'react';
import { describe, it, expect, vi } from 'vitest';
import { render, screen, fireEvent } from '@testing-library/react';
import { MeetingList } from '@/renderer/components/ui/MeetingList';
import type { Recording } from '@/renderer/hooks/useMeetings';

const makeMeeting = (overrides: Partial<Recording> = {}): Recording => ({
  id: 'meeting-1',
  title: 'Team Standup',
  startedAt: Date.now(),
  endedAt: Date.now() + 60000,
  durationMs: 60000,
  transcript: 'We discussed the sprint goals.',
  chunks: [],
  type: 'meeting',
  summary: '',
  summaryStatus: 'pending',
  decisions: [],
  topics: [],
  actionItems: [],
  audioSource: 'mic',
  participants: [],
  tags: [],
  ...overrides,
});

describe('MeetingList — row content', () => {
  it('renders the meeting title and duration', () => {
    const meeting = makeMeeting({ title: 'Budget Review', durationMs: 21000 });
    render(
      <MeetingList
        meetings={[meeting]}
        selectedId={null}
        onSelect={vi.fn()}
        onNewRecording={vi.fn()}
      />,
    );

    expect(screen.getByText('Budget Review')).toBeTruthy();
    expect(screen.getByText('21s')).toBeTruthy();
  });

  it('renders each topic as a pill (duplicated for the marquee loop)', () => {
    // Topics are retroactively generated by the structured summarizer during
    // enrichment (see src/main/services/enrichment.ts) — the list row's tag
    // pills read from meeting.topics, not the still-unused meeting.tags field.
    const meeting = makeMeeting({ topics: ['design-review', 'q3-planning'] });
    render(
      <MeetingList
        meetings={[meeting]}
        selectedId={null}
        onSelect={vi.fn()}
        onNewRecording={vi.fn()}
      />,
    );

    // TagMarquee duplicates the tag list so the CSS loop wraps seamlessly.
    expect(screen.getAllByText('design-review')).toHaveLength(2);
    expect(screen.getAllByText('q3-planning')).toHaveLength(2);
  });

  it('renders no tag pills when a meeting has no topics yet', () => {
    const meeting = makeMeeting({ topics: [] });
    const { container } = render(
      <MeetingList
        meetings={[meeting]}
        selectedId={null}
        onSelect={vi.fn()}
        onNewRecording={vi.fn()}
      />,
    );

    expect(container.querySelectorAll('.tag-marquee-track').length).toBe(0);
  });
});

describe('MeetingList — type grouping', () => {
  it('renders a meeting under "Meetings" and a dictation under "Dictations"', () => {
    const meeting = makeMeeting({
      id: 'm1',
      title: 'Team Standup',
      type: 'meeting',
    });
    const dictation = makeMeeting({
      id: 'd1',
      title: 'Grocery list',
      type: 'dictation',
    });
    render(
      <MeetingList
        meetings={[meeting, dictation]}
        selectedId={null}
        onSelect={vi.fn()}
        onNewRecording={vi.fn()}
      />,
    );

    expect(screen.getByText('Meetings')).toBeTruthy();
    expect(screen.getByText('Dictations')).toBeTruthy();
    expect(screen.getByText('Team Standup')).toBeTruthy();
    expect(screen.getByText('Grocery list')).toBeTruthy();
  });

  it('shows an empty-state line under a section with zero items', () => {
    const meeting = makeMeeting({
      id: 'm1',
      title: 'Team Standup',
      type: 'meeting',
    });
    render(
      <MeetingList
        meetings={[meeting]}
        selectedId={null}
        onSelect={vi.fn()}
        onNewRecording={vi.fn()}
      />,
    );

    expect(screen.getByText('Meetings')).toBeTruthy();
    expect(screen.getByText('Dictations')).toBeTruthy();
    expect(screen.getByText('No dictations yet')).toBeTruthy();
  });

  it('keeps search results within their own type section', () => {
    const meeting = makeMeeting({
      id: 'm1',
      title: 'Budget Review',
      type: 'meeting',
    });
    const dictation = makeMeeting({
      id: 'd1',
      title: 'Grocery list',
      type: 'dictation',
    });
    render(
      <MeetingList
        meetings={[meeting, dictation]}
        selectedId={null}
        onSelect={vi.fn()}
        onNewRecording={vi.fn()}
      />,
    );

    const input = screen.getByPlaceholderText('Search...');
    fireEvent.change(input, { target: { value: 'budget' } });

    expect(screen.getByText('Budget Review')).toBeTruthy();
    expect(screen.queryByText('Grocery list')).toBeNull();
    expect(screen.getByText('No dictations match your search')).toBeTruthy();
  });
});
